version: '3.8'
networks: 
  backend:
    name: sample-php-form.backend
volumes:
  app-data:
services:
  apache:
    container_name: sample-php-form.apache
    build: ./
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - 8080:80
    volumes:
      - ../htdocs/dist:/var/www/html
    networks:
      - backend
  mailhog:
    container_name: sample-php-fpm.mailhog
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - backend
